### ISSUE TITLE
CartoDBfy is incomplete for CartoDB GDAL Driver imports using GDAL 2.2.0dev and 2.1.0 

### ISSUE THREAD

**Issue by ztephm** [CartoDB/gdal#2]
@rafatower (or please let me know who to assign to)
cc @jsanz 

When using the [CartoDB GDAL driver](http://gdal.org/1.11/ogr/drv_cartodb.html) with [latest stable GDAL 2.1.0](https://trac.osgeo.org/gdal/wiki/DownloadSource) to import a WGS 84/EPSG:4326 shapeflle, the dataset appears in my CartoDB account with proper the_geom values but null the_geom_webmercator values. 

This is also happening with dev version (trunk branch) of GDAL 2.2.0. If GDAL 2.0.0 is used the_geom and the_geom_webmercator are populated properly.

## Context
* account = stephaniemongon
* used [this shapefile](http://52.26.186.219/internships/useit/sites/scec.usc.edu.internships.useit/files/presentations/California%20Cities%20(points).zip)

  ```
  gdalsrsinfo california_cities_points3.shp
  ```
    * PROJ.4 : '+proj=longlat +datum=WGS84 +no_defs '
      OGC WKT :
      GEOGCS["GCS_WGS_1984",
      DATUM["WGS_1984",
        SPHEROID["WGS_84",6378137.0,298.257223563]],
      PRIMEM["Greenwich",0.0],
      UNIT["Degree",0.0174532925199433]]

## Process
* attempt 1:

```
ogr2ogr --config CARTODB_API_KEY myapikey -nln "is_geomweb_there_3" -t_srs "EPSG:4326" -f CartoDB "CartoDB:stephaniemongon" california_cities_points3.shp
```

* attempt 2:

```
ogr2ogr --config CARTODB_API_KEY myapikey -nln "is_geomweb_there_5" -f CartoDB "CartoDB:stephaniemongon" california_cities_points3.shp
```

## Expected result
The_geom_webmercator will automatically be populated upon import, because there is enough info in the file to populate the_geom.

## Current result
* https://team.cartodb.com/u/stephaniemongon/tables/is_geomweb_there_3
* https://team.cartodb.com/u/stephaniemongon/tables/is_geomweb_there_5
* ![is_geomweb_there_3](https://cloud.githubusercontent.com/assets/1779444/15948717/5cc31530-2e70-11e6-9255-d5aeb9878f66.png)
* ![screen shot 2016-06-09 at 6 31 54 pm](https://cloud.githubusercontent.com/assets/1779444/15948737/7f414898-2e70-11e6-91d8-b7e30d63dbfb.png)

We know we can use SQL to update the_geom_webmercator, but is this an issue with our driver, & can it be fixed?

**Comment by rafatower** [comment]
This seems to be a regression in the ogr cartodb driver. You should report it to the mainstream project:

https://trac.osgeo.org/gdal

This project is only here to facilitate packaging of the binaries in our platform.

I'll try to gather some more debugging information in order to speed up its resolution.

**Comment by rafatower** [comment]
I got some traces (tcpdump) to understand the issue and this is what I got:

* With ogr2ogr from gdal version `2.1.0+svn.33718` WRONG:

```sql
q=BEGIN;
INSERT INTO "california_cities_points3" ("longitude", "latitude", "name_0", "namelsad", "the_geom")
VALUES (-117.40921400000, 34.58276900000, 'California', 'Adelanto', '0101000020E61000002EC4EA8F305A5DC0B20FB22C984A4140'),
(-118.76167500000, 34.15333900000, 'California', 'Agoura Hills', '0101000020E610000092CB7F48BFB05DC0C619C39CA0134140'),
(-122.24163600000, 37.76520600000, 'California', 'Alameda', '0101000020E61000005262D7F6768F5EC0FA592C45F2E14240'),
(-122.29774700000, 37.88686900000, 'California', 'Albany', '0101000020E6100000DADE6E490E935EC0096B63EC84F14240'),
(-118.12701400000, 34.09528600000, 'California', 'Alhambra', '0101000020E6100000960854FF20885DC022E2E654320C4140'),

-- ...

COMMIT;&api_key=<my_api_key>
```

then:
```sql
q=SELECT cdb_cartodbfytable('california_cities_points3')&api_key=<my_api_key>
```


---


* With ogr2ogr from gdal version `2.1.0+svn.29639` OK:

first it cartodbfies:
```sql
q=SELECT cdb_cartodbfytable('california_cities_points3')&api_key=<my_api_key>>
```

then it inserts the data:
```sql
q=BEGIN;
INSERT INTO "california_cities_points3" ("longitude", "latitude", "name_0", "namelsad", "the_geom", "cartodb_id") VALUES (-117.40921400000, 34.58276900000, 'California', 'Adelanto', '0101000020E61000002EC4EA8F305A5DC0B20FB22C984A4140', nextval('california_cities_points3_cartodb_id_seq'));
INSERT INTO "california_cities_points3" ("longitude", "latitude", "name_0", "namelsad", "the_geom", "cartodb_id") VALUES (-118.76167500000, 34.15333900000, 'California', 'Agoura Hills', '0101000020E610000092CB7F48BFB05DC0C619C39CA0134140', nextval('california_cities_points3_cartodb_id_seq'));
INSERT INTO "california_cities_points3" ("longitude", "latitude", "name_0", "namelsad", "the_geom", "cartodb_id") VALUES (-122.24163600000, 37.76520600000, 'California', 'Alameda', '0101000020E61000005262D7F6768F5EC0FA592C45F2E14240', nextval('california_cities_points3_cartodb_id_seq'));
INSERT INTO "california_cities_points3" ("longitude", "latitude", "name_0", "namelsad", "the_geom", "cartodb_id") VALUES (-122.29774700000, 37.88686900000, 'California', 'Albany', '0101000020E6100000DADE6E490E935EC0096B63EC84F14240', nextval('california_cities_points3_cartodb_id_seq'));

-- ...

COMMIT;&api_key=<my_api_key>
```

so that in previous versions the trigger applies keeping `the_geom` and `the_geom_webmercator` in sync.

**Comment by rafatower** [comment]
@iriberri what do you think? This ticket is mostly a matter of assigning responsibilities to components. IMHO it would be fair to assume that if `the_geom` and `the_geom_webmercator` exist they should be already in sync before cartodbfy'ing (isn't it documented somewhere as such?)

**Comment by rafatower** [comment]
The behavior change was introduced here: https://trac.osgeo.org/gdal/changeset/30283

**Comment by iriberri** [comment]
Some background info:

The `the_geom_webmercator` column is expected to be populated (if the column already exists in the table) by the `update_the_geom_webmercator` trigger that the CartoDBfication is creating in the target table.

In the CartoDBfication, if the `the_geom_webmercator` column does not exist, the table gets rewritten and this column gets populated and added (See the `CDB_TransformToWebmercator` function [here](https://github.com/CartoDB/cartodb-postgresql/blob/224b2ce39504f974cc47602fd49c3fecb60a5b27/scripts-available/CDB_CartodbfyTable.sql#L957-L961)).

The CartoDBfy function **does not** validate the data in `the_geom_webmercator`, just defines the mechanisms to include it if it's missing.

What it seems to be happening here is that the table is created with an empty `the_geom_webmercator` column and CartoDBfied after all the insertions. In this scenario, the CartoDBfy function will recognise the `the_geom_webmercator` column and it will asume it's okay, so it will just include the triggers that won't have any effect because the INSERTS/UPDATES have already been performed on table creation (all those INSERT INTO that Rafa pointed out).

My conclusion, or what I suggest is:
* When the table is created, if nobody is going to fill in the appropriate data in `the_geom_webmercator` column, it should just not be added
* The CartoDBfication will add and generate the `the_geom_webmercator` column when it sees it's missing

`the_geom_webmercator`, as well as `the_geom` and `cartodb_id` are system columns in CartoDB. If they exist, they shall respect the [system' conventions](https://github.com/CartoDB/cartodb-postgresql/blob/36ac831bd14b296f22767949503f9989f62d1442/doc/cartodbfy-requirements.rst#valid-cartodb-tables) (they should be populated correctly). If they don't, the CartoDBfy function will generate them, leaving a working table.

**Comment by rafatower** [comment]
For the record, the table creation query sent through the sql api:

**Comment by ztephm** [comment]
Thank you both! Please let me know if you need me to help test anything.

**Comment by rafatower** [comment]
For the record: the way it creates the sequence (see the queries above) leaves it without a clear owner, which afffects cartodbfy'ation as well.

This is how the sequence is left:
```
# SELECT pg_get_serial_sequence('california_cities_points3', 'cartodb_id');
 pg_get_serial_sequence 
------------------------
 
(1 row)
```

and this is what it should do to relate it to the table and column (if it makes any sense at all to create , drop and then recreate again):
```
# ALTER SEQUENCE california_cities_points3_cartodb_id_seq OWNED BY california_cities_points3.cartodb_id;
ALTER SEQUENCE

# SELECT pg_get_serial_sequence('public."california_cities_points3"', 'cartodb_id');
             pg_get_serial_sequence              
-------------------------------------------------
 public.california_cities_points3_cartodb_id_seq
(1 row)
```

We'll have to look for workarounds for it, as we're talking about released versions of gdal.

**Comment by rafatower** [comment]
Fixes going here: https://trac.osgeo.org/gdal/ticket/6565

Scheduled for next release.

**Comment by jsanz** [comment]
excellent Rafa!! I'll try against trunk when I have the chance

On Thu, Jun 30, 2016 at 6:26 PM, Rafa de la Torre <notifications@github.com>
wrote:

> Fixes going here: https://trac.osgeo.org/gdal/ticket/6565
>
> Scheduled for next release.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/gdal/issues/2#issuecomment-229712306>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AALfaFl_rUvX5Idh2cx4DO1ySRSFMJ7Nks5qQ-43gaJpZM4IzL09>
> .
>



-- 
Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data

**Comment by rafatower** [comment]
I tested it against `r34515` (tip of `2.1` branch) which includes the fix and it works OK. So we're good for the next gdal release.
